In [39]:
import nltk
#we download the names
#Check default download directory?
print(nltk.data.path)

#download name data/models from nltk. More details can be found in below link:
#https://github.com/nltk/nltk/wiki/Frequently-Asked-Questions-(Stackoverflow-Edition)
#nltk.download('names')

['/home/shravan/nltk_data', '/usr/nltk_data', '/usr/share/nltk_data', '/usr/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']


[nltk_data] Downloading package names to /home/shravan/nltk_data...
[nltk_data]   Unzipping corpora/names.zip.


True

In [13]:
# Mixing and shuffling the data.
import numpy as np
import random
from nltk.corpus import names

#extractin male names
male_names    = [(name, 'male') for name in names.words('male.txt')]
female_names  = [(name, 'female') for name in names.words('female.txt')]

#combining the names and randominzing them
labeled_names = male_names + female_names
random.shuffle(labeled_names)

#converting to the numpy array
labeled_names=np.array(labeled_names)
labeled_names[0:10,:]

array([['Tremain', 'male'],
       ['Christal', 'female'],
       ['Janna', 'female'],
       ['Fernando', 'male'],
       ['Alston', 'male'],
       ['Gordan', 'male'],
       ['Audrie', 'female'],
       ['Alisun', 'female'],
       ['Davidson', 'male'],
       ['Tabby', 'female']], dtype='<U15')

In [17]:
def gender_features(name):
    return name[-1].lower()

print(gender_features("shravan"))

# syntax of numpy_array --> np.array( specifies_row_number, specifies_column_number    )
# labeled_names[:, 0]   --> all rows and oth column elements
name_letters  = [gender_features(name) for name in labeled_names[:,0]]

#remove empty strings
"""
a = ["a", "b", "c", " ", "e"]
print(a)
a = np.array(a)
ind = np.where( (a!=" ")==True)[0]
print(ind)
print(a[ind])

"""
name_letters  = np.array(name_letters)
ind           = np.where((name_letters!=' ')==True)[0]
name_letters  = name_letters[ind]

X = name_letters
X = np.array(X).reshape(-1,1)

#converting to numerical matrix. male=0, female=1
y = np.where(labeled_names[ind,1]=='male',0,1)

y

n


array([0, 1, 1, ..., 1, 1, 0])

In [35]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(X)
X2 =  lb.transform(X)
# each character is represented with a number. Example: a=1, b=2, c=3...etc
print(X2)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
from sklearn.model_selection import train_test_split

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y, test_size=0.4, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [26]:
## General ML Recipe algorithm
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
clf = MultinomialNB(alpha=0.1,fit_prior=True) # Note alpha
clf.fit(X_train2, y_train2)
y_train_pred = clf.predict(X_train2)
y_test_pred  = clf.predict(X_test2)

In [27]:
np.set_printoptions(suppress=True)
print(clf.predict_proba(X_test2))
X_test

[[0.56875737 0.43124263]
 [0.41603725 0.58396275]
 [0.41603725 0.58396275]
 ...
 [0.01660785 0.98339215]
 [0.56875737 0.43124263]
 [0.16302179 0.83697821]]


array([['n'],
       ['y'],
       ['y'],
       ...,
       ['a'],
       ['n'],
       ['i']], dtype='<U1')

In [28]:
# accuracy = correct_prediction / total_prediction
print("accuracy training set ", accuracy_score(y_train_pred,y_train2))
print("accuracy test set ",accuracy_score(y_test_pred,y_test2))

accuracy training set  0.7649527806925498
accuracy test set  0.7595972309628697


In [29]:
CC=confusion_matrix(y_test2,y_test_pred)
CC

array([[ 797,  400],
       [ 364, 1617]])

In [38]:
test1 = lb.transform([''])
clf.predict(test1)

array([0])