## Classyfing Mushrooms
We first consider the following small (artificial) dataset

$$
\begin{array}{ccc}
EdibleOrPoisonous & red-color & capSurface\\
e &                y     & s\\   
 e &                y    & s    \\
  e &                  y   & y     \\
 p &                  n    & f    \\
  p &                 y    & s    \\
  p &                  n    & f \\
\end{array}
$$

We first write it down in Python using a numpy 2D-array. We then convert it into a Pandas Dataframe, that is another type of data-container.

In [92]:
import pandas as pd
import numpy as np
#e->1,p->0
#y->1,n->0
#s->0,y->1,f->2
data=np.array([
    [1 , 1 , 0],
    [1 , 1 , 0],
    [1 , 1 , 1],
    [0 , 0 , 2],
    [0 , 1 , 0],
    [0 , 0 , 2]])

#we convert it into a pandas Dataframe
df=pd.DataFrame(data,columns=['EdibleOrPoisonous','RedColor','CapSurface'])
df

EdibleOrPoisonous  RedColor  CapSurface
0                  1         1           0
1                  1         1           0
2                  1         1           1
3                  0         0           2
4                  0         1           0
5                  0         0           2

The first column (0,1,2,...) is the index column and then we have the three columns 'EdibleOrPoisonous','RedColor','CapSurface'

In [94]:
#We prepare the data in the format that is needed by MultinomialNB
train_df=df.copy()
col=np.array(['RedColor','CapSurface'])
for f in range(1,df.shape[1]) :
    for elem in df.iloc[:,f].unique():
        train_df[col[f-1]+'_'+str(elem)] = (train_df.iloc[:,f]==elem)+0.0

#we drop the original columns 'RedColor','CapSurface'
train_df=train_df.drop(columns=col)
train_df

EdibleOrPoisonous  RedColor_1  RedColor_0  CapSurface_0  CapSurface_1  \
0                  1         1.0         0.0           1.0           0.0   
1                  1         1.0         0.0           1.0           0.0   
2                  1         1.0         0.0           0.0           1.0   
3                  0         0.0         1.0           0.0           0.0   
4                  0         1.0         0.0           1.0           0.0   
5                  0         0.0         1.0           0.0           0.0   

   CapSurface_2  
0           0.0  
1           0.0  
2           0.0  
3           1.0  
4           0.0  
5           1.0

In [95]:
#we prepare the input data (features) and output data (class)
X=train_df.iloc[:,1:].values #.values converts pandas back to numpy
y=train_df.iloc[:,0].values

In [96]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB(alpha=0)#note that we do not use any reguralisation 
clf.fit(X,y)
clf.predict_proba(np.array([[1,0,1,0,0]]))

/home/benavoli/anaconda3/envs/mypy/lib/python3.7/site-packages/sklearn/naive_bayes.py:480: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


array([[0.14285714, 0.85714286]])

In [97]:
clf=MultinomialNB(alpha=0)
clf.fit(X,y)
clf.predict_proba(np.array([[1,0,0,1,0]]))

/home/benavoli/anaconda3/envs/mypy/lib/python3.7/site-packages/sklearn/naive_bayes.py:480: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


array([[0., 1.]])

Note the sharp probability, the probability is 1 for edible

In [134]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB(alpha=1) #we add the reguralisation in this case
clf.fit(X,y)
clf.predict_proba(np.array([[1,0,0,1,0]]))

array([[0.2, 0.8]])

Note that the probability is not sharp anymore

## Real example
We use a UCI dataset https://archive.ics.uci.edu/ml/datasets/mushroom

In [115]:
df = pd.read_csv('./mushroom-classification/mushrooms.csv')#put here the folder tha includes your data
from sklearn.utils import shuffle
#we shuffle the dataset
df = shuffle(df, random_state=42)
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
1971     e         f           f         n       f    n               f   
6654     p         f           s         e       f    y               f   
5606     p         x           y         n       f    f               f   
3332     e         f           y         g       t    n               f   
6988     p         f           s         e       f    s               f   
5761     p         x           y         n       f    y               f   
5798     p         x           s         g       t    f               f   
3064     p         x           y         y       f    f               f   
1811     e         f           f         n       t    n               f   
3422     e         f           y         n       t    n               f   
3555     e         f           f         e       t    n               f   
5317     p         b           y         w       t    n               f   
706      e         b           y         y       t    l               f   
1075     e         f           s         g       f    n               f   
233      e         f           f         n       f    n               f   
3480     e         f           y         g       t    n               f   
1557     e         b           y         y       t    a               f   
7634     p         k           y         e       f    f               f   
828      e         x           s         w       t    l               f   
2534     e         f           f         g       t    n               f   
736      e         x           f         w       t    a               f   
856      e         f           s         y       t    l               f   
7088     p         k           s         e       f    s               f   
3624     e         x           f         n       t    n               f   
5129     p         x           s         b       t    f               f   
1656     e         x           s         n       f    n               f   
2574     e         x           y         n       t    n               f   
3113     e         f           y         e       t    n               f   
2753     e         x           y         g       t    n               f   
1566     p         f           y         n       t    p               f   
...    ...       ...         ...       ...     ...  ...             ...   
5051     p         x           y         e       f    y               f   
5311     p         b           y         n       f    n               f   
2433     e         x           f         g       t    n               f   
6949     p         k           s         e       f    f               f   
7581     e         k           f         w       f    n               f   
5611     p         f           f         g       f    f               f   
2391     e         x           f         n       t    n               f   
769      e         b           s         w       t    a               f   
7476     p         x           s         e       f    y               f   
1685     e         f           s         n       f    n               f   
130      e         b           s         w       t    l               f   
7831     e         f           s         n       f    n               a   
2919     e         f           y         n       t    n               f   
3171     e         f           y         n       t    n               f   
3444     p         x           s         w       f    c               f   
6231     p         f           y         n       f    y               f   
5578     e         x           y         c       f    n               f   
4426     p         f           f         y       f    f               f   
5334     p         f           s         g       t    f               f   
466      e         x           s         w       t    a               f   
6265     p         f           s         e       f    s               f   
5734     e         k          

In [116]:
#we divide the dataset in training and testing
train_df = df[:7000]
test_df = df[7000:]
print(test_df.shape)
train_df

(1124, 23)


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
1971     e         f           f         n       f    n               f   
6654     p         f           s         e       f    y               f   
5606     p         x           y         n       f    f               f   
3332     e         f           y         g       t    n               f   
6988     p         f           s         e       f    s               f   
5761     p         x           y         n       f    y               f   
5798     p         x           s         g       t    f               f   
3064     p         x           y         y       f    f               f   
1811     e         f           f         n       t    n               f   
3422     e         f           y         n       t    n               f   
3555     e         f           f         e       t    n               f   
5317     p         b           y         w       t    n               f   
706      e         b           y         y       t    l               f   
1075     e         f           s         g       f    n               f   
233      e         f           f         n       f    n               f   
3480     e         f           y         g       t    n               f   
1557     e         b           y         y       t    a               f   
7634     p         k           y         e       f    f               f   
828      e         x           s         w       t    l               f   
2534     e         f           f         g       t    n               f   
736      e         x           f         w       t    a               f   
856      e         f           s         y       t    l               f   
7088     p         k           s         e       f    s               f   
3624     e         x           f         n       t    n               f   
5129     p         x           s         b       t    f               f   
1656     e         x           s         n       f    n               f   
2574     e         x           y         n       t    n               f   
3113     e         f           y         e       t    n               f   
2753     e         x           y         g       t    n               f   
1566     p         f           y         n       t    p               f   
...    ...       ...         ...       ...     ...  ...             ...   
5431     p         f           y         y       f    f               f   
6842     p         f           y         e       f    f               f   
4621     p         f           f         y       f    f               f   
6809     p         x           s         e       f    y               f   
364      e         x           s         y       t    a               f   
3287     e         f           y         e       t    n               f   
2125     e         x           y         e       t    n               f   
4123     p         f           f         y       f    f               f   
4569     p         x           f         y       f    f               f   
525      e         b           s         y       t    l               f   
4821     p         f           f         y       f    f               f   
55       e         b           y         y       t    a               f   
638      e         x           s         n       f    n               f   
302      e         x           s         y       t    l               f   
2766     p         x           f         g       f    f               f   
5811     p         f           s         w       t    f               f   
1276     e         x           f         n       f    n               f   
7608     p         k           y         n       f    y               f   
4720     p         f           f         y       f    f               f   
2055     e         f           f         w       f    n               f   
5376     p         b           y         p       t    n               f   
6947     p         k          

In [117]:
#from this we can derive the accuracy of the majority class classifier (0.51)
print(train_df['class'].value_counts(normalize=1))

#we know convert the class variable 'e', 'p', 'u' into numerical values: 0,1,2
#and we save the result in the list target
target=[]
for i in range(len(train_df['class'].values)):
    if train_df['class'].values[i]=='e':
        target.append(0)
    if train_df['class'].values[i]=='p':
        target.append(1)
    if train_df['class'].values[i]=='u':
        target.append(2)
        
#we convert the list into an array
target=np.array(target)
target

e    0.515714
p    0.483143
u    0.001143
Name: class, dtype: float64


array([0, 1, 1, ..., 1, 1, 0])

In [118]:
#we delete the class column because now it is stored in target
del train_df['class']

#we transform inputs for multinomialNB
cols = list(train_df)
for f in cols :
    for elem in df[f].unique():
        train_df[f+'_'+str(elem)] = (train_df[f]==elem)
#we delete old columns
for f in cols:
    del train_df[f]
train_df.head()
train_df=train_df+0.0 #this converts Boolean to 0 and 1
train_df

/home/benavoli/anaconda3/envs/mypy/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


cap-shape_f  cap-shape_x  cap-shape_b  cap-shape_k  cap-shape_s  \
1971          1.0          0.0          0.0          0.0          0.0   
6654          1.0          0.0          0.0          0.0          0.0   
5606          0.0          1.0          0.0          0.0          0.0   
3332          1.0          0.0          0.0          0.0          0.0   
6988          1.0          0.0          0.0          0.0          0.0   
5761          0.0          1.0          0.0          0.0          0.0   
5798          0.0          1.0          0.0          0.0          0.0   
3064          0.0          1.0          0.0          0.0          0.0   
1811          1.0          0.0          0.0          0.0          0.0   
3422          1.0          0.0          0.0          0.0          0.0   
3555          1.0          0.0          0.0          0.0          0.0   
5317          0.0          0.0          1.0          0.0          0.0   
706           0.0          0.0          1.0          0.0          0.0   
1075          1.0          0.0          0.0          0.0          0.0   
233           1.0          0.0          0.0          0.0          0.0   
3480          1.0          0.0          0.0          0.0          0.0   
1557          0.0          0.0          1.0          0.0          0.0   
7634          0.0          0.0          0.0          1.0          0.0   
828           0.0          1.0          0.0          0.0          0.0   
2534          1.0          0.0          0.0          0.0          0.0   
736           0.0          1.0          0.0          0.0          0.0   
856           1.0          0.0          0.0          0.0          0.0   
7088          0.0          0.0          0.0          1.0          0.0   
3624          0.0          1.0          0.0          0.0          0.0   
5129          0.0          1.0          0.0          0.0          0.0   
1656          0.0          1.0          0.0          0.0          0.0   
2574          0.0          1.0          0.0          0.0          0.0   
3113          1.0          0.0          0.0          0.0          0.0   
2753          0.0          1.0          0.0          0.0          0.0   
1566          1.0          0.0          0.0          0.0          0.0   
...           ...          ...          ...          ...          ...   
5431          1.0          0.0          0.0          0.0          0.0   
6842          1.0          0.0          0.0          0.0          0.0   
4621          1.0          0.0          0.0          0.0          0.0   
6809          0.0          1.0          0.0          0.0          0.0   
364           0.0          1.0          0.0          0.0          0.0   
3287          1.0          0.0          0.0          0.0          0.0   
2125          0.0          1.0          0.0          0.0          0.0   
4123          1.0          0.0          0.0          0.0          0.0   
4569          0.0          1.0          0.0          0.0          0.0   
525           0.0          0.0          1.0          0.0          0.0   
4821          1.0          0.0          0.0          0.0          0.0   
55            0.0          0.0          1.0          0.0          0.0   
638           0.0          1.0          0.0          0.0          0.0   
302           0.0          1.0          0.0          0.0          0.0   
2766          0.0          1.0          0.0          0.0          0.0   
5811          1.0          0.0          0.0          0.0          0.0   
1276          0.0          1.0          0.0          0.0          0.0   
7608          0.0          0.0          0.0          1.0          0.0   
4720          1.0          0.0          0.0          0.0          0.0   
2055          1.0          0.0          0.0          0.0          0.0   
5376          0.0          0.0          1.0          0.0          0.0   
6947          0.0          0.0          0.0          1.0          0.0   
5145          0.0          1.0          0.0          0.0        

In [119]:
from sklearn.naive_bayes import MultinomialNB

#we train the model
clf = MultinomialNB() #by default alpha=1.0
train_x = train_df.values
clf.fit(train_x,target)




MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [120]:
#this is the accuracy in the training dataset
from sklearn.metrics import accuracy_score 
y_pred=clf.predict(train_x)
accuracy_score(y_pred,target)

0.9478571428571428

In [121]:
#we transform the test dataset
test_y = test_df['class']
del test_df['class']
for f in cols :
    for elem in df[f].unique():
        test_df[f+'_'+str(elem)] = (test_df[f]==elem)
for f in cols:
    del test_df[f]
test_df

/home/benavoli/anaconda3/envs/mypy/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


cap-shape_f  cap-shape_x  cap-shape_b  cap-shape_k  cap-shape_s  \
2286         True        False        False        False        False   
2261        False         True        False        False        False   
5240         True        False        False        False        False   
7228         True        False        False        False        False   
2296        False         True        False        False        False   
6937        False         True        False        False        False   
5932        False         True        False        False        False   
1753        False         True        False        False        False   
5197        False        False        False         True        False   
1968         True        False        False        False        False   
7055        False        False        False         True        False   
3117         True        False        False        False        False   
2393        False         True        False        False        False   
523         False         True        False        False        False   
6376         True        False        False        False        False   
6788         True        False        False        False        False   
6981        False        False        False         True        False   
5524         True        False        False        False        False   
6677         True        False        False        False        False   
3900        False         True        False        False        False   
7569        False        False        False         True        False   
4699        False         True        False        False        False   
5585        False         True        False        False        False   
7168         True        False        False        False        False   
3122        False         True        False        False        False   
6777        False         True        False        False        False   
4156         True        False        False        False        False   
1969         True        False        False        False        False   
671          True        False        False        False        False   
4188        False         True        False        False        False   
...           ...          ...          ...          ...          ...   
5051        False         True        False        False        False   
5311        False        False         True        False        False   
2433        False         True        False        False        False   
6949        False        False        False         True        False   
7581        False        False        False         True        False   
5611         True        False        False        False        False   
2391        False         True        False        False        False   
769         False        False         True        False        False   
7476        False         True        False        False        False   
1685         True        False        False        False        False   
130         False        False         True        False        False   
7831         True        False        False        False        False   
2919         True        False        False        False        False   
3171         True        False        False        False        False   
3444        False         True        False        False        False   
6231         True        False        False        False        False   
5578        False         True        False        False        False   
4426         True        False        False        False        False   
5334         True        False        False        False        False   
466         False         True        False        False        False   
6265         True        False        False        False        False   
5734        False        False        False         True        False   
3092         True        False        False        False        

Now we check the accuracy for unseen data, that is we make prediction for the test-dataset and then we compute the accuracy

In [122]:
test_x = test_df.values
#we convert the class 'e','p','u' into 0,1,2
test_y1=[]
for i in range(len(test_y)):
    if test_y.values[i]=='e':
        test_y1.append(0)
    if test_y.values[i]=='p':
        test_y1.append(1)
    if test_y.values[i]=='u':
        test_y1.append(2)
        
#we convert the list into an array
test_y1=np.array(test_y1)

#we compute the prediction
y_pred=clf.predict(test_x)
#we compute the accuracy 
accuracy_score(y_pred,test_y1)

0.949288256227758

The classifier is performing very-well. Let's see the confusion matrix

In [126]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y1,y_pred)

array([[594,   4,   0],
       [ 45, 473,   8],
       [  0,   0,   0]])

In [125]:
? confusion_matrix

It never correctly classifies the unknowns, but there are only few cases. The problem is that there 45 cases where a poisonous mushroom is classified as edible. This is dangerous. The confusion matrix in this case gives us more information than accuracy, because the errors are not the same. That is it is worse if we classify poisonous as edible than vice versa.

## Question 
Your goal here is to reduce the dangerous misclassifications to zero by changing the prediction rule. To do that, we can use a threshold. For instance, consider these probabilities for the class 0 (edible), 1 (poisonous), 2 (unknown)


In [132]:
clf.predict_proba(test_x[2:3,:])

array([[0.13368851, 0.86630996, 0.00000153]])

The MultinomialNB classifier in this case returns the class "1" (poisonous), becuase it has the greatest probability

In [133]:
clf.predict(test_x[2:3,:])

array([1])

We could make decisions only if the probability is greater than a large threshold. 
For instance, the threshold could be 0.999.

Given the probabilities for all the test inputs

In [136]:
np.set_printoptions(suppress=True)#this suppresses the scientific notation in the visualisation of the porbabilities
proba = clf.predict_proba(test_x)
proba

array([[0.99999999, 0.00000001, 0.        ],
       [0.99999491, 0.00000509, 0.        ],
       [0.13368851, 0.86630996, 0.00000153],
       ...,
       [0.99999983, 0.00000002, 0.00000015],
       [0.        , 0.99958562, 0.00041438],
       [0.99996303, 0.00003652, 0.00000045]])

write down a function that implements the above decision.
More precisely, if $[p1,p2,p3]$ is one row in the above matrix of probabilities, the decision is

`
if p1>threshold
    prediction =0
elif p2>threshold
    prediction =1
elif p3>threshold
    prediction =2
else
    prediction = -1 #this "-1" means none of the above cases.
`    

In other words,  You need to write down a function that implements that decision rule for all elements in `proba` and then compute the resulting accuracy for all the cases where the classifier made a decision (that is it returns something different from -1).

You should then verify that when threshold=1/3, you  get the same accuracy as 

In [137]:
#we compute the prediction
y_pred=clf.predict(test_x)
#we compute the accuracy 
accuracy_score(y_pred,test_y1)

0.949288256227758